default:
  before_script:
    - source ~/.bashrc

variables:
  AWS_PROFILE: access_dev

stages:
  - lint
  - deploy

lint-terraform:
  stage: lint
  only:
    - master
    - merge_requests
  script:
    - make fmt-check
    - MODULE=0_account_init make terraform-validate
    - MODULE=1_network make terraform-validate
    - MODULE=2_directory make terraform-validate

deploy-terraform:
  stage: deploy
  rules:
    - if: '$CI_OPEN_MERGE_REQUESTS && $TEST_MR_DEPLOYMENT_ON_DEV == "true"'
      when: manual
    - if: '$CI_COMMIT_REF_NAME == "master"'
  script:
    - echo "Deploying the 1_network layer"
    - MODULE=1_network make plan
    - MODULE=1_network make deploy
    - echo "Deploying the 2_directory layer"
    - MODULE=2_directory make plan
    - MODULE=2_directory make deploy
