default:
  before_script:
    - source ~/.bashrc

variables:
  AWS_PROFILE: access_dev

stages:
  - lint
  - deploy

lint-terraform:
  stage: lint
  only:
    - master
    - merge_requests
  script:
    - make tf-fmt-check
    - BUILD_ENV=dev MODULE=0_account_init make tf-validate
    - BUILD_ENV=dev MODULE=1_network make tf-validate
    - BUILD_ENV=dev MODULE=2_directory make tf-validate

deploy-terraform:
  stage: deploy
  rules:
    - if: '$CI_OPEN_MERGE_REQUESTS && $TEST_MR_DEPLOYMENT_ON_DEV == "true"'
      when: manual
    - if: '$CI_COMMIT_REF_NAME == "master"'
  script:
    - echo "Deploying the 1_network layer"
    - BUILD_ENV=dev MODULE=1_network make tf-plan
    - BUILD_ENV=dev MODULE=1_network make tf-apply EXTRA_ARGS="-auto-approve=true"
    - echo "Deploying the 2_directory layer"
    - BUILD_ENV=dev MODULE=2_directory make tf-plan
    - BUILD_ENV=dev MODULE=2_directory make tf-apply EXTRA_ARGS="-auto-approve=true"
