default:
  before_script:
    - source ~/.bashrc
    - cat .tool-versions | xargs -L 1 asdf install

stages:
  - lint
  - deploy-dev
  - deploy-int

lint-terraform:
  stage: lint
  variables:
    AWS_PROFILE: access_dev
  only:
    - master
    - merge_requests
  script:
    - make tf-fmt-check
    - BUILD_ENV=dev MODULE=0_account_init make tf-validate
    - BUILD_ENV=dev MODULE=1_network make tf-validate
    - BUILD_ENV=dev MODULE=2_directory make tf-validate

deploy-dev:
  stage: deploy-dev
  variables:
    AWS_PROFILE: access_dev
  rules:
    - if: '$CI_OPEN_MERGE_REQUESTS && $TEST_MR_DEPLOYMENT_ON_DEV == "true"'
      when: manual
    - if: '$CI_COMMIT_REF_NAME == "master"'
  script:
    - echo "Deploying the 1_network layer"
    - BUILD_ENV=dev MODULE=1_network make tf-apply EXTRA_ARGS="-auto-approve=true"
    - echo "Deploying the 2_directory layer"
    - BUILD_ENV=dev MODULE=2_directory make tf-apply EXTRA_ARGS="-auto-approve=true"

deploy-int:
  stage: deploy-int
  variables:
    AWS_PROFILE: access_int
  only:
    - int
  script:
    - echo "Deploying the 1_network layer"
    - BUILD_ENV=int MODULE=1_network make tf-apply EXTRA_ARGS="-auto-approve=true"
    - echo "Deploying the 2_directory layer"
    - BUILD_ENV=int MODULE=2_directory make tf-apply EXTRA_ARGS="-auto-approve=true"
