default:
  before_script:
    - source ~/.bashrc

variables:
  AWS_PROFILE: access_dev

stages:
  - lint
  - deploy

lint-terraform:
  stage: lint
  only:
    - master
    - merge_requests
  script:
    - make fmt-check
    - MODULE=0_account_init make terraform-validate
    - MODULE=1_network make terraform-validate
    - MODULE=2_directory make terraform-validate

deploy-1-network:
  stage: deploy
  only:
    - master
  script:
    - echo "Deploying the 1_network layer"
    - MODULE=1_network make plan
    - MODULE=1_network make deploy

deploy-2-directory:
  stage: deploy
  only:
    - master
  script:
    - echo "Deploying the 2_directory layer"
    - MODULE=2_directory make plan
    - MODULE=2_directory make deploy
